### ISSUE TITLE
Reset cache via terminal/command line

### ISSUE THREAD

**Issue by schickling** [zendtech/ZendOptimizerPlus#112]
There should be a way to reset the cache for any php instances (CLI/FPM...) via the command line. Just running `php -r 'opcache_reset();'` doesn't work _yet_

More workarounds and discussion:
http://stackoverflow.com/questions/17716639/opcache-clean-cache-in-php5-4-and-lower/

**Comment by girvan** [comment]
@muhqu php-fpm-cli is awesome and it also solve my several problem, thank you.

**Comment by daniel-gomes-sociomantic** [comment]
`php-fpm-cli` worked for me as well, cheers!

**Comment by alexVauch** [comment]
@muhqu your script is awesome! Thank you.
Also for those who get message such as: `/var/run/php5-fpm.sock not found` but the file exists. Check the file permissions. Your user should have permissions to read the file.

**Comment by terraboops** [comment]
If you're using `mod_php` running inside of Apache, you can run this from the command-line:

`service httpd reload`
or
`apachectl graceful`

This will gracefully restart Apache -- it should cause no disruption for connected users.

**Comment by sir-gon** [comment]
@muhqu works like a charm!!! perfect for my continuous integration setup...
For debian 8 jessie requires the **libfcgi0ldbl** package to get the cgi-fcgi command working inside the script.

**Comment by diegonalvarez** [comment]
@muhqu thanks ! Awesome script, works for me in my first try.
Best regards.

**Comment by fmonts** [comment]
For those who get the

> cgi-fcgi: command not found

error, you have to 

> apt-get install libfcgi0ldbl

**Comment by muhqu** [comment]
…and for those on RHEL/CentOS:

```
yum --enablerepo=epel install fcgi
```

**Comment by szepeviktor** [comment]
See https://github.com/gordalina/cachetool

**Comment by jeffmcneill** [comment]
Note that the following will all clear opcache:

`apachectl -k stop` + `apachectl -k start`
`apachectl -k graceful`
`apachectl -k restart`
`apachectl -k graceful-stop` + `apachectl -k start`

The second and fourth options are gentle with connected users.

More about the `apachectl` commands here: https://httpd.apache.org/docs/2.4/stopping.html

**Comment by TerryE** [comment]
> `apachectl -k graceful-stop + apachectl -k start`

So does `reboot`, but neither option is sensible for a production service, is it?  Wrapping up a `php opcache_reset()` call in an authenticated access script or one of the other patterns discussed above is a far sounder approach.

**Comment by jeffmcneill** [comment]
Please explain why graceful-stop + start is not a viable approach. It is made for such circumstances.

**Comment by TerryE** [comment]
OK, this is a personal view, but the 2.4 graceful stop / restart is a _lot_ better than a normal stop in that it 
allows Apache to bring its child processes to an orderly exit so the you can then restart everything.  However, from a queueing perspective what this does is to collapse the overall webserver throughput during the bounce.  This is fine for services with a light transaction rate, or  where request rates have a diurnal cycle and you want to do a release or some other S/W activity which requires to the bounce the caches during "quiet" hours.  It has the great advantage that it allows all child processes to bounce their caches synchronously. But this is some way from what control engineers would class as a "bumpless handover".

**Comment by jeffmcneill** [comment]
I don't see how there is a throughput collapse wiht `apachectl -k graceful-stop + apachectl -k start`. That doesn't make sense. One process stops responding to new requests while a new process starts responding to new requests. But if you don't like that, then just go with `apachectl -k graceful` which is what its namesake suggests. The same apache process reloads a new configuration (including a new opcache). With a multisite configuration, it seems that one has to have an opcache flush command run against each site, whereas at the level of the webserver, this can be done in one place at one time.

**Comment by TerryE** [comment]
I think that you are trying to describe  the `apachectl -k graceful` function which is a graceful restart (Signal: **USR1** not **WINCH**), though even this has worker brownout issues according to some of the comments.  PHP is usually built in none-threaded mode, and uses a lot of child workers.
