### ISSUE TITLE
path issue when using phar

### ISSUE THREAD

**Issue by arabcoders** [zendtech/ZendOptimizerPlus#115]
It seems there is problem with loading Phar files when using zend opcache, i trace it down to  path issues.

for example when you use the following script in Mutliple Hosts Environment (MHE), it does not work and the autoload does not find and scripts, and my guess is that the opcache is loading the other websites phar and they have different owner & permmsions so its fails to load them.

```
<?php
$baseDir = './';
include("phar://{$baseDir}include/twig.phar/Twig/Autoloader.php");
Twig_Autoloader::register();
$loader = new Twig_Loader_Filesystem($baseDir . '/tpl/');

?>
```

but changing the baseDir to 

```
<?php
$baseDir = '/home/user/public_html/';
include("phar://{$baseDir}include/twig.phar/Twig/Autoloader.php");
$loader = new Twig_Loader_Filesystem($baseDir . '/tpl/');
?>
```

it seems to work alright, and Yes i tried the first script with opcache disabled and it worked

the same problem happens with APC as well.

**Comment by curry684** [comment]
It should be noted that this issue is definitely not fixed. I was still experiencing it this morning on a PHP 7.0.15 server, 2 different websites containing an `aws.phar` file, and depending on which got loaded first after restart the other site bugs out permanently with permission errors.

**Comment by Spotnyk** [comment]
I have also been experiencing this issue with Guzzle and Bugsnag Phar implementations on 7.1.7
