### ISSUE TITLE
Unable to allocate shared memory segment error

### ISSUE THREAD

**Issue by crabel** [zendtech/ZendOptimizerPlus#134]
I currently see these errors in the logfile:

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/gd.so' - libjpeg.so.62: failed to map segment from shared object: Cannot allocate memory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/imagick.so' - libfftw3.so.3: failed to map segment from shared object: Cannot allocate memory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/intl.so' - libicudata.so.36: failed to map segment from shared object: Cannot allocate memory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/mysql.so' - libmysqlclient.so.18: failed to map segment from shared object: Cannot allocate memory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/mysqli.so' - libmysqlclient.so.18: failed to map segment from shared object: Cannot allocate memory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/pdo_mysql.so' - /usr/lib64/php/modules/pdo_mysql.so: failed to map segment from shared object: Cannot allocate memory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/pdo_sqlite.so' - /usr/lib64/php/modules/pdo_sqlite.so: failed to map segment from shared object: Cannot allocate memory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/phar.so' - /usr/lib64/php/modules/phar.so: failed to map segment from shared object: Cannot allocate memory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/wddx.so' - /usr/lib64/php/modules/wddx.so: failed to map segment from shared object: Cannot allocate memory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/xmlreader.so' - /usr/lib64/php/modules/xmlreader.so: failed to map segment from shared object: Cannot allocate memory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/xmlwriter.so' - /usr/lib64/php/modules/xmlwriter.so: failed to map segment from shared object: Cannot allocate memory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/xsl.so' - /usr/lib64/php/modules/xsl.so: failed to map segment from shared object: Cannot allocate memory in Unknown on line 0
Sun Sep 22 12:22:21 2013 (8552): Fatal Error Unable to allocate shared memory segment of 205520896 bytes: shmat: Cannot allocate memory (12)

This error repeats every couple of seconds:

Sun Sep 22 12:22:21 2013 (8554): Fatal Error Unable to allocate shared memory segment of 205520896 bytes: shmat: Cannot allocate memory (12)
PHP Warnings
Sun Sep 22 12:22:21 2013 (8556): Fatal Error Unable to allocate shared memory segment of 205520896 bytes: shmat: Cannot allocate memory (12)
PHP Warnings
Sun Sep 22 12:22:29 2013 (8558): Fatal Error Unable to allocate shared memory segment of 205520896 bytes: shmat: Cannot allocate memory (12)
PHP Warnings
Sun Sep 22 12:22:32 2013 (8562): Fatal Error Unable to allocate shared memory segment of 205520896 bytes: shmat: Cannot allocate memory (12)
PHP Warnings
Sun Sep 22 12:22:34 2013 (8565): Fatal Error Unable to allocate shared memory segment of 205520896 bytes: shmat: Cannot allocate memory (12)
PHP Warnings
Sun Sep 22 12:22:37 2013 (8567): Fatal Error Unable to allocate shared memory segment of 205520896 bytes: shmat: Cannot allocate memory (12)
...

I have noticed these errors first last Monday, Tuesday evening they stopped and reapeared yesterday afternoon. The weird thing is, everything seems to work. No 500 internal server errors or something, nobody complains.

I don't understand why I get these errors. My config:

opcache.memory_consumption=196
opcache.enable=1
opcache.use_cwd=1
opcache.validate_timestamp=0  
opcache.revalidate_freq=180    ; seconds
opcache.revalidate_path=0
opcache.dups_fix=0
opcache.log_verbosity_level=1
opcache.interned_strings_buffer=8  
opcache.max_accelerated_files=4000
opcache.max_wasted_percentage=25
opcache.consistency_checks=0
opcache.force_restart_timeout=60
opcache.blacklist_filename=
opcache.fast_shutdown=1
opcache.enable_cli=1
opcache.enable_file_override=1
opcache.optimization_level=0xfffffbbf
opcache.enable_slow_optimizations=1

Server is CentOS5.9 with PHP 5.4.19

Maybe I don't understand correctly what Zend optimizer does. I thought that it allocates the cache once at startup and later just reattaches. Why should it try to allocate that amout again? Or is the error message misleading?

According to phpinfo Zend seems to work: (I just restarted, it usually caches about 1500 files after a couple of days)
Opcode Caching  Up and Running
Optimization    Enabled
Startup     OK
Shared memory model     mmap
Cache hits  1587373
Cache misses    1459
Used memory     110901784
Free memory     88870072
Wasted memory   5749040
Cached scripts  1139
Cached keys     1358
Max keys    7963
OOM restarts    0
Hash keys restarts  0
Manual restarts     0 

Any ideas how I could find out what happens?

**Comment by wenchangming211** [comment]
Could you tell me how to solve the problem?

Request Method: | GET
-- | --
http://192.168.111.142/
1.8
ImportError
/usr/local/lib/python2.7/lib-dynload/future_builtins.so: failed to map segment from shared object: Cannot allocate memory
/usr/local/lib/python2.7/site-packages/reportlab/__init__.py in  <module>, line 31
/usr/local/bin/uwsgi
2.7.13
