### ISSUE TITLE
fast_shutdown = 1 crashes

### ISSUE THREAD

**Issue by jswinghammer** [zendtech/ZendOptimizerPlus#146]
Running PHP 5.4.20 and zend op cache 7.0.2. When we enable fast_shutdown = 1 and the number of objects created on a page gets large (more than 1900 or so objects) we see 500 errors occur during random parts of the page. This wasn't happening on all the pages but it was always correlated to the total number of objects that were getting instantiated on the page. Below that 1900 count I wasn't seeing the error at all. Turning off the fast_shutdown setting resolved the 500 errors.

For example the HTML output will look normal enough until the footer and then we'll see the standard apache 500 error text appear. Nothing gets logged in this case and no core files are created. I'm happy to answer any questions or give you more information.

**Comment by hugochinchilla** [comment]
I was having trouble with segmentation faults after upgrading to php 5.5.23, setting fast_shutdown = 0 seems to solve the issue.

More infor here: https://bugs.php.net/bug.php?id=69190

**Comment by pixelchutes** [comment]
Recently migrated a few projects on a legacy server _(still running on PHP 5.3, using  [ZendOpcache 7.0.5](https://pecl.php.net/package/ZendOpcache)_ to PHP 5.6 with built-in ZendOpcache 7.0.6-dev.

On occasion, started seeing random 500 errors or "zend_mm_heap corrupted" warning in the error logs that were never experienced before.

Re-tuning the opcache configuration (increasing `max_accelerated_files`, and setting `opcache.fast_shutdown=0`) appears to have resolved the issues so far.

**Comment by scottsb** [comment]
@pixelchutes: it looks like you might be running into this issue (which may or may not be related to what this ancient issue discusses): https://bugs.php.net/bug.php?id=65590

**Comment by pixelchutes** [comment]
Thanks for linking that here @scottsb! I did come across Bug 65590 during my review, definitely seems related. However, I've seen very few `zend_mm_heap corrupted` errors in comparison to other symptoms I ended up posting in more detail here: https://github.com/zendtech/ZendOptimizerPlus/issues/187#issuecomment-225048350

As long as there are no "corrupt" worker processes (see above link), everything appears to function as expected. Still trying to identify the _source_ of the impacted php-fpm worker(s), and whether or not it's OPcache related.

**Comment by duzun** [comment]
Is it still the case in PHP 7+ ?

**Comment by mfn** [comment]
From https://www.php.net/manual/en/opcache.configuration.php#ini.opcache.fast-shutdown
> This directive has been removed in PHP 7.2.0. A variant of the fast shutdown sequence has been integrated into PHP and will be automatically used if possible. 

So _maybe_ this whole thing doens't apply anymore for PHP >= 7.2

**Comment by danger89** [comment]
Issue is still open? This is issue still present on PHP 8.1?

**Comment by melroy89** [comment]
This issue should be closed now.

**Comment by dstogov** [comment]
``opcache.fast_shutdown`` was removed in PHP-7.2
