### ISSUE TITLE
Version 7.0.4 disappeared?

### ISSUE THREAD

**Issue by lukaszwit** [zendtech/ZendOptimizerPlus#175]
Hi,
I'm pretty sure that there was a version 7.0.4 at http://pecl.php.net/package-changelog.php?package=ZendOpcache and this is the version which I use on production but... it seems that 7.0.4 disappeared?

**Comment by shaunfreeman** [comment]
when compiling php > 5.5 the use '--with-opcache' flag and add 'zend_extension=opcache.so' to your php ini and you will have opcache. When compiling PHP 5.6 then you get OPCache 7.0.4-dev

**Comment by laruence** [comment]
7.0.5 was released on PECL
