### ISSUE TITLE
新版opcache出现很多signal退出信号

### ISSUE THREAD

**Issue by kn007** [zendtech/ZendOptimizerPlus#176]
原谅我使用中文，英文书写不好。十分抱歉。

我遇到的问题是，使用了opcache7.0.3和7.0.4-dev，在php-fpm.log可以看到大量的signal 6 (SIGABRT)，可以访问，但在流量大的时候有点卡。当我禁用了opcache时，正常。没有其他的加载项（.so）。

重启php-fpm(FastCGI)，会出现signal 11 (SIGSEGV)，这时候网页访问都是502，nginx的error.log没有错误。偶尔重启后是出现signal 7 (SIGBUS)，这时候跟signal 6的情况差不多，可以访问，大流量有点卡。

错误的php-fpm.log示例：
WARNING: [pool www] child 5012 exited on signal 6 (SIGABRT) after 1.100957 seconds from start

PHP版本是5.5.11。尝试过5.5.9、5.5.10。也是不行。
系统是Centos6.4 X64， 内核是2.6.32-358.0.1.el6.x86_64。
nginx版本是1.7.0，试过1.5.6。仍然是错误。
mysql版本是5.6。也是尝试多个小版本号（5.6.X），结果不行。

如果在其他条件不变，使用PHP5.5.6，那么opcache版本是7.0.3-dev，这个时候是正常的。没有任何退出信号，在php-fpm.log里，访问也很正常。

如果使用5.5.11，或者说>5.5.6的版本，将opcache版本降级为7.0.2，那么也是正常的。

感觉好奇怪，不知有没有朋友遇到过？

愿意提供VPS帐号，以供解决。

另外，还有一个小问题。。。
如果PHP5.5.12使用listen = /tmp/php-cgi.sock，那么会出现权限拒绝。看了下 /tmp/php-cgi.sock 权限是660，使用端口模式正常。当版本<5.5.12正常，权限都是666。
我的问题是。。。是不是用port好过file(unix)？

谢谢！

**Comment by ghost** [comment]
没有结果就关了?
