### ISSUE TITLE
Zend OPcache and HHVM both together

### ISSUE THREAD

**Issue by aditya-** [zendtech/ZendOptimizerPlus#199]
Hi ,

my environment 

`ubuntu 14.04` , `php 5.5` , `nginx 1.7.6`

    PHP 5.5.19-1+deb.sury.org~trusty+1 (cli) (built: Nov 19 2014 19:33:43) 
    Copyright (c) 1997-2014 The PHP Group
    Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
         with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2014, by Zend Technologies

I just want to use both zend opcache and HHVm together. 

Is this allowed ? will i get better performance with this option

or this method not required ?

or if i can use both  then will it eat more resources ? 

anyone please replay

**Comment by aditya-** [comment]
i thought both are php byte code compilers ... so this thing allowed ?

**Comment by Majkl578** [comment]
It makes no sense.
HHVM and PHP are fundamentally different in terms of implementation. HHVM compiles code into bytecode and JITs it for best performance.
I'd suggest reading [this great article](http://hhvm.com/blog/6323/the-journey-of-a-thousand-bytecodes) about how HHVM processes the scripts.

**Comment by aditya-** [comment]
@Majkl578  Thanks for your replay. I just have a doubt that Opcache stores  precompiled script
bytecode in the shared memory. where HHVM also compiles code into byte code . thats the reason why i got confused ? 
are they different in compilation

**Comment by laruence** [comment]
HHVM is not PHP, Opcache is not for HHVM, thanks :)
