### ISSUE TITLE
Is zendopcache-7.0.4 availble as .deb package?

### ISSUE THREAD

**Issue by enoch85** [zendtech/ZendOptimizerPlus#204]
I have Ubuntu Server 14.04 (PHP 5.5.9) and want to change from APCu to ZendOpcache 7.0.4 instead.

Is there any .deb package available for download?

**Comment by enoch85** [comment]
Never mind. Found it, sorry for unnecessary issue.

**Comment by Reiner030** [comment]
thanks for sharing the link to the found place ^^

Here what I researched within longer time:
1) there was a which for a debian package: https://lists.debian.org/debian-devel/2013/02/msg00244.html
2) a nice manual howto extract/use the needed files from zend server:
https://ckon.wordpress.com/2013/02/12/manually-install-zend-optimizer-plus-on-php/

3) this nice howto download from Zend and use:
http://en.ispdoc.com/index.php/Installing_Zend_Optimizer
and the location for it is:
http://www.zend.com/en/products/loader/downloads

But thats not the here offered ZendOptimizerPlus but ZendGuardLoader (which could / would have the Optimizer included)... But it seems be the alternative choice - as here also given with config lines:

https://www.howtoforge.com/community/threads/zend-optimizer-perfect-server-debian-squeeze-debian-6-0.57202/

Works for me, so 1st it's also "solved" - now SIGSEGVs are gone .. 
But it would be nice to have a Debian package with ZendOptimizerPlus of this repository if someone knows about such project. Thx. ;)

**Comment by Reiner030** [comment]
ah... finally found... https://www.dotdeb.org/2015/05/22/php-5-4-41-for-wheezy-and-squeeze/

=> The "problem" is: Because of the crashes we had to dowgrade back to 5.4.40 which hasn't Zend Opcache compiled in... But since it's now solved we would go back to latest security fix with Optimizer installed.
