### ISSUE TITLE
Opcache and Zend engine version

### ISSUE THREAD

**Issue by sadlyblue** [zendtech/ZendOptimizerPlus#212]
HI,
Not sure this is the right place, but can't get help anywhere else.
I installed the opcache with success (i think). But i keep getting the error of the Zend Engine outdated and i don't know how to updated.
I'm running a Centos 6 server with PHP 5.4, Apache 2.4, Mysql 5.5.
Please help.
Thanks

**Comment by TerryE** [comment]
Sorry but this issues list is for (potential) bug in Opcache itself. It is not the right place for admin / howto related issues.  Why not try ServeFault or StackOverflow?
