### ISSUE TITLE
OPcache status is unavailable in shutdown

### ISSUE THREAD

**Issue by szepeviktor** [zendtech/ZendOptimizerPlus#217]
```php
function o1_opcache() {
    var_export( opcache_get_status() ); // false
}
register_shutdown_function( 'o1_opcache' );
```

PHP 7.0.0-dev (cli) (built: Aug 17 2015 19:10:40)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0-dev, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies

**Comment by laruence** [comment]
I can not reproduce this with php7, anyway, this repo is only for the supporting of using opcache with php5.4- 

since php5.5, php already have bundled opcache, which is you are playing with. so , you should report bugs of that opcache in bugs.php.net or issues on github.com/php/php-src

thanks

**Comment by szepeviktor** [comment]
Thank you.
https://bugs.php.net/bug.php?id=70357
