### ISSUE TITLE
Error for make

### ISSUE THREAD

**Issue by Anoxia** [zendtech/ZendOptimizerPlus#221]
## making output:

    /Users/Anoxia/Downloads/zendopcache-7.0.5/zend_persist.c:153:8: error: use of undeclared identifier 'IS_CONSTANT_ARRAY'
                    case IS_CONSTANT_ARRAY:
                        ^
    1 error generated.
    make: *** [zend_persist.lo] Error 1
    make: *** Waiting for unfinished jobs....
    /Users/Anoxia/Downloads/zendopcache-7.0.5/zend_persist_calc.c:110:8: error: use of undeclared identifier    'IS_CONSTANT_ARRAY'
                    case IS_CONSTANT_ARRAY:
                        ^
    1 error generated.
    make: *** [zend_persist_calc.lo] Error 1
    /Users/Anoxia/Downloads/zendopcache-7.0.5/ZendAccelerator.c:39:10: fatal error: 'TSRM/tsrm_virtual_cwd.h' file not found
    #include "TSRM/tsrm_virtual_cwd.h"
            ^
    /Users/Anoxia/Downloads/zendopcache-7.0.5/zend_accelerator_module.c:31:10: fatal error: 'TSRM/tsrm_virtual_cwd.h' file not  found
    #include "TSRM/tsrm_virtual_cwd.h"
            ^
    1 error generated.
    make: *** [zend_accelerator_module.lo] Error 1
    1 error generated.
    make: *** [ZendAccelerator.lo] Error 1

System: Mac OS X 10.11.2
GCC:

    Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
    Apple LLVM version 7.0.2 (clang-700.1.81)
    Target: x86_64-apple-darwin15.2.0
    Thread model: posix

**Comment by laruence** [comment]
please use bundled opcache (since PHP5.5 opcache is bundled as ext/opcache).. this repo is only for php below 5.5

**Comment by nikic** [comment]
@laruence Can we maybe add a more prominent warning at the top of the README that this repo is dead and people should use bundled opcache?

**Comment by laruence** [comment]
@nikic of course, https://github.com/zendtech/ZendOptimizerPlus/commit/3b16ca512290b0416baf02962beedc703147a97a
