### ISSUE TITLE
undefined symbol: zend_new_interned_string

### ISSUE THREAD

**Issue by ck-on** [zendtech/ZendOptimizerPlus#72]
First error I have seen after running the trunk from 3/18/2013

_Failed loading .../opcache.so:  .../opcache.so: undefined symbol: zend_new_interned_string_

Running on php-fpm 5.4 trunk from same date.

Been running for a week without problems and even after that error it seems like it is still humming along.

This error seems to appear in google previously going back a year or more from the original optimizer+ ?

**Comment by zhoubeiqing** [comment]
I also encountered this problem.
