### ISSUE TITLE
Feature request:  restrict execution of opcache api functions to specific path/script

### ISSUE THREAD

**Issue by ck-on** [zendtech/ZendOptimizerPlus#89]
It would be a helpful security addition to be able to restrict the script path the api functions are executed from. On shared servers this would probably be a must.

ie.  restrict to the path starting with this subdirectory:

```
  opcache.restrict_api = /home/admin/
```

or even restrict to just one very specific script:

```
  opcache.restrict_api = /home/admin/www/control-panel.php
```

and this global php.ini directive should be made impossible to override locally

Hopefully you have easy access to the script_name/execution path and then in theory this would be fairly straightforward to implement?

Thanks for considering!

**Comment by szepeviktor** [comment]
@dstogov Is it possible to block API usage for an FPM pool?

**Comment by szepeviktor** [comment]
May I try this?

```ini
opcache.restrict_api = /does-not/exist
```

**Comment by dstogov** [comment]
You don't have to ask me to try. :)
I think this should solve work.
